---
site_name: "Muryoutaisuu's Notes on CNCF & KubeCon 2019, Barcelona"
theme:
  name: readthedocs
  highlightjs: true
repo_url: https://github.com/muryoutaisuu/cncf_conf_2019_barcelona_notes
nav:
  - Home: "index.md"
  - "Lightning Talks": "lightning-talks.md"
  - "Keynotes": "keynotes.md"
  - "Sessions": "sessions.md"
  - "Keywords": "keywords.md"
